# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: dparv's tech ramblings
email: me@dparv.dev
description: >- # this means to ignore newlines until "baseurl:"
  IT by profession, skydiver at heart. Automating my life as much as
  possible, as I am the lazier person you will ever meet. But still some
  good ideas might come out of it.

baseurl: "" # the subpath of your site, e.g. /blog
relative_url: ""
url: "https://dparv.dev" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: diko.parvanov
linkedin_username: dparv
github_username:  dparv

social-network-links:
  rss: true
  email: "me@dparv.dev"
  github: dparv
  linkedin: dparv
  facebook: diko.parvanov
  instagram: diko.parvanov
  spotify: 12169068346

share-links-active:
  facebook: true
  linkedin: true

avatar: "assets/images/me_thumb.jpg"

navbar-links:
  Blog: "/"
  Tags: "tags"
  About: "about"

excerpt_length: 100
# Build settings
#theme: minima
#minima:
#  skin: dark
#theme: enfield-jekyll-theme
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate-v2
  - jekyll-sitemap

round-avatar: true

post_search: true

navbar-col: "#242728"
navbar-text-col: "#c0bab2"
navbar-border-col: "#3a3e41"
page-col: "#181a1b"
text-col: "#c0bab2"
link-col: "#be873e"
hover-col: "#506681"
footer-col: "#242728"
text-col: "#c0bab2"
footer-link-col: "#506681"
footer-hover-col: "#506681"

site-css:
  - "/assets/css/custom-styles.css"

pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/blog/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

link-tags: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - publish_dparv.dev.sh
  - preview.sh
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
